version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.70
    - 0.12.71
    - 0.12.73
    - 0.12.74
    - 0.12.75
    - 0.12.76
    - 0.12.77
    - 0.12.78
    - 0.12.79
    - 0.12.80
    - 0.12.81
    - 0.12.82
    - 0.12.83
    - 0.12.84
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.2
    - 2.18.3
    - 2.18.4
    - 2.18.5
  - dependency-name: cloudinary/cloudinary_php
    versions:
    - 1.20.0
    - 2.0.1
    - 2.0.2
    - 2.0.3
    - 2.0.4
    - 2.1.0
  - dependency-name: phpmailer/phpmailer
    versions:
    - 6.2.0
    - 6.3.0
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.2
    - 5.2.3
