#!/bin/bash

./tests.sh curlTest/*
TEST=$?
echo "retour tests"
if [ $TEST -ne 0 ]
then
    printf "\n\033[41mAborting pushing due to errors in tests\033[0m\n"
else
    printf "\n\033[42mEverythings fine, pushing now\033[0m\n"
fi
exit $TEST
